### ISSUE TITLE
how to fix this problem. 

### ISSUE THREAD

**Issue by hanjay3757** [DominikLingenover/DMNK-Tools#11]
Im using houdini 19.0.383
when I follow install direction but when I click tool  this show up
Traceback (most recent call last):
  File "dmnk_material_importer", line 1, in <module>
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\material_importer\material_importer_core.py", line 6, in <module>
    import icons
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'icons'

**Comment by Treadstoun** [comment]
Hello. Do you find solution ?

**Comment by ktonini** [comment]
To fix this for speedtree_importer_core.py, change -
`import icons`
to -
`from .icons import *`

Then in speedtree_importer/icons.py, add a "b" before the quote for each variable-
`qt_resource_data = b"\`
`qt_resource_name = b"\`
`qt_resource_struct = b"\`

For material_importer_core.py, change -
`import icons`
`import name_list`
to -
`from .icons import *`
`from .name_list import *`

Then in material_importer/icons.py, add a "b" before the quote for each variable-
`qt_resource_data = b"\`
`qt_resource_name = b"\`
`qt_resource_struct = b"\`
